version: "3.7"
services:
  frontend:
    container_name: frontend
    build: frontend
    stdin_open: true
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-graphql
  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - react-graphql
      - graphql-mongo
    environment:
      NODE_ENV: production
  mongo:
    container_name: mongo-final-project
    image: "mongo:4.4.3"
    volumes:
      - ./data:/data/db
    networks:
      - graphql-mongo

networks:
  react-graphql:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  graphql-mongo: